language: java
jdk: oraclejdk7
sudo: true
before_install: 
  - apt-get -y install sshpass
  - eval `ssh-agent -s`
  - chmod 600 ~/.ssh/config
  - openssl aes-256-cbc -K $encrypted_6aecf171dcc3_key -iv $encrypted_6aecf171dcc3_iv -in data.pem.enc -out data.pem -d
  - cp data.pem ~/.ssh/
  - chmod 600 ~/.ssh/data.pem
  - ssh-add ~/.ssh/data.pem
  - ls -al
  - scp shareUmbrella.war ec2-user@ec2-54-238-225-208.ap-northeast-1.compute.amazonaws.com:/home/ec2-user
  - sshpass -p shareumbrella ssh -i data.pem root@ec2-54-238-225-208.ap-northeast-1.compute.amazonaws.com
  - cd /home/ec2-user
  - rm -rd /var/lib/tomcat7/shareUmbrella
  - mv shareUmbrella.war /var/lib/tomcat7/webapps/
  - service tomcat7 restart
script: ant generate.service
