language: java
jdk: oraclejdk7
before_install: 
  - sudo apt-get update -qq
  - sudo apt-get install sshpass -qq
  - eval `ssh-agent -s`
  - sudo chmod 600 ~/.ssh/config
  - openssl aes-256-cbc -K $encrypted_6aecf171dcc3_key -iv $encrypted_6aecf171dcc3_iv -in data.pem.enc -out data.pem -d
  - sudo cp data.pem ~/.ssh/
  - sudo chmod 600 ~/.ssh/data.pem
  - sudo ssh-add ~/.ssh/data.pem
  - ls -al
  - sudo scp shareUmbrella.war ec2-user@ec2-54-238-225-208.ap-northeast-1.compute.amazonaws.com:/home/ec2-user
  - sudo sshpass -p shareumbrella ssh -i data.pem root@ec2-54-238-225-208.ap-northeast-1.compute.amazonaws.com
  - sudo cd /home/ec2-user
  - sudo rm -rd /var/lib/tomcat7/shareUmbrella
  - sudo mv shareUmbrella.war /var/lib/tomcat7/webapps/
  - sudo service tomcat7 restart
script: ant generate.service
