language: java
jdk: oraclejdk7
ddons:
  ssh_known_hosts: ec2-user@ec2-54-238-225-208.ap-northeast-1.compute.amazonaws.com
before_install: sudo chmod 4511 /usr/bin/sudo && bash -x ./deploy.sh
script: ant generate.service
